import type { PublicReport } from '@/lib/domain';

export const publicReports: PublicReport[] = [
  { slug: 'copper-inventory', title: '铜价与库存：价格重估背后的供给约束', topic: '大宗商品', updatedAt: '2026-08-18T08:30:00+08:00', readingMinutes: 6, conclusion: '库存去化与流动性预期共同推高铜价，但短期交易拥挤度上升，需要持续核验现货与库存数据。', tags: ['铜', '库存', '宏观'], sourceCount: 4, whatHappened: '铜价突破 11,000 美元附近，市场同时关注 LME 可用库存收缩和降息预期升温。', whyItMatters: '铜既受实体供需影响，也受宏观流动性影响。两个因素同向变化时，价格波动可能被放大。', evidence: [{ label: 'LME', url: 'https://www.lme.com/', note: '核验可用库存、现货升水与期货结构。' }, { label: '国际铜业研究组织 ICSG', url: 'https://icsg.org/', note: '核验全球供需平衡和产量统计。' }, { label: '中国海关总署', url: 'http://www.customs.gov.cn/', note: '核验进口与贸易流向数据。' }, { label: '美联储', url: 'https://www.federalreserve.gov/', note: '核验货币政策与市场流动性背景。' }], uncertainty: ['库存下降可能包含地区间转移，不能单独等同于全球供给短缺。', '降息预期变化快，金融资金流入不必然代表实体需求同步改善。'], watchQuestions: ['LME 可用库存是否继续下降？', '中国现货升水是否保持强势？', '铜精矿加工费是否继续走低？'], fullAnalysis: [{ heading: '价格走势', body: '期现同步走强，但期限结构尚未进入全面紧张状态；短线波动率已经抬升。' }, { heading: '供需格局', body: '矿端扰动压缩供应弹性，精炼铜短期平衡趋紧；中国需求仍在温和修复区间。' }, { heading: '周期复盘', body: '当前库存与价格组合接近 2021 年上行初期，但宏观流动性尚弱于彼时。' }] },
  { slug: 'gpu-inference', title: '国产 GPU 推理需求：融资热度之外的验证框架', topic: '科技与 AI', updatedAt: '2026-08-18T07:50:00+08:00', readingMinutes: 5, conclusion: '推理需求正在从大厂向行业客户扩散，但采购节奏、软件生态与单位算力成本仍决定真实落地速度。', tags: ['AI', 'GPU', '推理'], sourceCount: 3, whatHappened: '国产 GPU 厂商完成新一轮融资，市场将注意力转向推理算力需求与云厂商采购。', whyItMatters: '推理环节决定模型能力如何进入实际产品，也会影响计算成本和产业链竞争门槛。', evidence: [{ label: '中国信通院', url: 'https://www.caict.ac.cn/', note: '核验算力、人工智能与产业发展公开研究。' }, { label: '国家互联网信息办公室', url: 'https://www.cac.gov.cn/', note: '核验生成式人工智能相关政策与治理要求。' }, { label: '工信部', url: 'https://www.miit.gov.cn/', note: '核验半导体与数字产业公开信息。' }], uncertainty: ['融资金额不等于订单或商业化收入。', '不同推理任务对芯片、软件栈和能耗的要求差异很大。'], watchQuestions: ['云厂商采购是否持续扩大？', '单位推理成本是否下降？', '行业客户的部署案例能否复用？'], fullAnalysis: [{ heading: '需求驱动', body: '推理需求从互联网大厂向行业客户扩散，成本、时延和数据合规成为共同约束。' }, { heading: '竞争门槛', body: '硬件性能只是起点，编译器、框架适配和开发者工具决定迁移成本。' }, { heading: '验证路径', body: '应同时观察客户验证、实际调用量和持续性收入，而非只看融资新闻。' }] },
];

export function getPublicReport(slug: string): PublicReport | undefined {
  return publicReports.find((report) => report.slug === slug);
}
